version: "3"
services:
  byeoldam-database:
    container_name: byeoldam-database
    build:
      dockerfile: Dockerfile
      context: ./backend/database
    image: lmw7414/byeoldam-database
    volumes:
      # 설정파일 저장될  위치
      - ./database/config:/etc/mysql/conf.d
      # DB 데이터 저장 디렉토리
      - ./database/data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=byeol_dam
      - MARIADB_USER=${SPRING_DATASOURCE_USERNAME}
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - "TZ=Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"

  byeoldam-frontend:
    container_name: "byeoldam-frontend"
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    command: "npm run dev"
    ports:
      - "5173:5173"
