version: "3"
services:
  byeoldam-database:
    container_name: byeoldam-database
    build:
      dockerfile: Dockerfile
      context: ./backend/database
    image: lmw7414/byeoldam-database
    volumes:
      # 설정파일 저장될  위치
      - ./backend/database/config:/etc/mysql/conf.d
      # DB 데이터 저장 디렉토리
      - /home/ubuntu/database/data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=byeol_dam
      - MARIADB_USER=${SPRING_DATASOURCE_USERNAME}
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - "TZ=Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  byeoldam-redis:
    container_name: byeoldam-redis
    build:
      dockerfile: Dockerfile
      context: ./backend/redis
    image: lmw7414/byeoldam-redis
    ports:
      - "6379:6379"
  byeoldam-app:
    container_name: byeoldam-app
    build: ./backend
    depends_on: # DB, Redis 실행 후 실행
      - byeoldam-database
      - byeoldam-redis
    image: lmw7414/byeoldam-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET_KEY_CODE=${JWT_SECRET_KEY_CODE}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
    ports:
      - "8081:8081"
    restart: always

  byeoldam-frontend:
    container_name: "byeoldam-frontend"
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    ports:
      - "5173:5173"
