version: "3"
services:
  byeoldam-database:
    container_name: byeoldam-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: lmw7414/byeoldam-database
    volumes:
      # 설정파일 저장될  위치
      - ./database/config:/etc/mysql/conf.d
      # DB 데이터 저장 디렉토리
      - ./database/data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=byeol_dam
      - MARIADB_USER=${SPRING_DATASOURCE_USERNAME}
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - "TZ=Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
  byeoldam-app:
    container_name: byeoldam-app
    build: .
    depends_on: # DB 실행 후 실행
      - byeoldam-database
    image: lmw7414/byeoldam-app
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET_KEY_CODE=${JWT_SECRET_KEY_CODE}
    ports:
      - "8080:8080"
    restart: always