
spring:
  profiles:
    active: local #default
    group:
      local:
        -common
      prod:
        -common


---
spring:
  config:
    active:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://local:3306/byeol_dam
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: byeoldam
    credentials:
      access-key : AKIA47SBDGN2JZ65CFX2
      secret-key : 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
    region:
      static : ap-northeast-2
      auto : false
    stack:
      auto : false