spring:
  profiles:
    active: local #default
    group:
      local:
        - common
      prod:
        - common


---
spring:
  config:
    activate:
      on-profile: common
    import: aws.properties
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
jwt:
  secret-key: ${JWT_SECRET_KEY_CODE}
  #30 days
  token:
    expired-time-ms: 2592000000
mail:
  host: smtp.gmail.com
  port: 587
  username: byeoldam309.official@gmail.com
  password: ${EMAIL_APP_PASSWORD}
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connection-timeout: 5000
        timeout: 5000
        write-timeout: 5000
  auth-code-expired-ms: 600000 #10분

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/byeol_dam?allowPublicKeyRetrieval=true&useSSL=false
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      url: redis://localhost:6379
      repositories:
        enabled: false

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://byeoldam-database:3306/byeol_dam?allowPublicKeyRetrieval=true&useSSL=false
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      url: redis://byeoldam-redis:6379
      repositories:
        enabled: false
server:
  port: 8081
